"""
keyword_engine.py
-----------------
Keyword and phrase libraries used by the NLP rule engine.

Defines three data structures:
  PRIORITY_KEYWORDS  — scored keyword sets for each priority level
                       (urgent, reply_now, read_later, ignore)
  SPECIAL_WEIGHTS    — high-impact substring phrases with fixed score boosts
  CATEGORY_KEYWORDS  — per-category keyword lists for classification
"""

PRIORITY_KEYWORDS = {
    "urgent": {
        "urgent": 35,
        "immediately": 35,
        "asap": 30,
        "critical": 40,
        "deadline": 40,
        "today": 30,
        "production issue": 40,
        "emergency": 45,
        "high priority": 30,
        "security breach": 45,
        "data loss": 45,
        "server down": 45,
        "outage": 45,
        "system failure": 40,
        "system crash": 40,
        "immediate attention": 35,
        "time sensitive": 30,
        "action required": 25,
        "expedite": 25,
        "escalate": 25,
        "blocking": 30,
        "blocker": 30,
        "critical bug": 35,
        "hotfix": 30,
        "security alert": 35,
        "unauthorized access": 40,
        "compromised": 35,
        "incident": 25,
        "disaster": 35,
        "fatal error": 35,
        "crucial": 25,
        "essential": 20,
        "mandatory": 25,
        "compulsory": 25,
        "end of day": 25,
        "eod": 20,
        "rush": 25,
        "instantly": 25,
        "promptly": 25,
        "quick response needed": 25,
        "do not delay": 30,
        "pressing": 20,
        "grave": 25,
        "severe": 25,
        "catastrophic": 40,
        "extreme": 25,
        "ultimatum": 35,
        "final notice": 35,
        "past due": 30,
        "overdue": 30,
        "suspension": 35,
        "breach": 30,
        "priority one": 35,
        "p1": 35,
        "resolve now": 30,
        "fix immediately": 35
    },
    "reply_now": {
        "reply": 20,
        "respond": 20,
        "approval": 25,
        "review": 15,
        "confirmation": 15,
        "schedule": 15,
        "meeting": 15,
        "feedback": 15,
        "accept": 15,
        "reject": 15,
        "confirm": 15,
        "verify": 15,
        "answer": 10,
        "question": 10,
        "inquiry": 10,
        "input needed": 20,
        "signature required": 25,
        "please sign": 20,
        "authorize": 20,
        "consent": 20,
        "validate": 15,
        "schedule a call": 15,
        "calendar invite": 15,
        "zoom link": 15,
        "google meet": 15,
        "availability": 15,
        "rsvp": 15,
        "attend": 10,
        "join": 10,
        "discuss": 15,
        "interview": 20,
        "appointment": 15,
        "booking": 15,
        "consultation": 15,
        "feedback requested": 15,
        "your thoughts": 15,
        "status update": 15,
        "project update": 15,
        "deliverable": 15,
        "action item": 15,
        "follow up": 15,
        "please check": 10,
        "look over": 10,
        "read and approve": 20,
        "provide feedback": 15,
        "your opinion": 10,
        "review attached": 15,
        "collaborate": 10,
        "partnership proposal": 15,
        "business inquiry": 15,
        "request for info": 15,
        "clarification": 10,
        "estimate": 15,
        "pricing quote": 15,
        "invoice query": 15,
        "payment confirmation": 10
    },
    "read_later": {
        "newsletter": -5,
        "weekly update": -5,
        "announcement": -5,
        "report": 5,
        "digest": -5,
        "documentation": 5,
        "training": 5,
        "policy": 0,
        "reference": 0,
        "tutorial": -5,
        "guide": -5,
        "handbook": -5,
        "manual": -5,
        "minutes of meeting": 5,
        "mom": 5,
        "summary": 0,
        "archive": -5,
        "log": 0,
        "receipt": 5,
        "invoice": 5,
        "statement": 5,
        "billing": 5,
        "subscription confirmed": -5,
        "order confirmation": 5,
        "shipping update": 5,
        "tracking number": 5,
        "delivered": 0,
        "package": 0,
        "welcome to": -10,
        "getting started": -5,
        "tips and tricks": -10,
        "best practices": -5,
        "case study": -5,
        "whitepaper": -5,
        "research": -5,
        "industry news": -5,
        "blog post": -10,
        "article": -10,
        "roadmap": -5,
        "release notes": -5,
        "changelog": -5,
        "features guide": -5,
        "user guide": -5,
        "knowledge base": -5,
        "faq": -5,
        "survey results": -5,
        "quarterly results": 5,
        "annual report": 5,
        "financial summary": 5,
        "presentation slides": 5,
        "memo": 5,
        "bulletin": -5,
        "briefing": 5,
        "press release": -5,
        "general info": -5
    },
    "ignore": {
        "promotion": -25,
        "sale": -25,
        "discount": -25,
        "offer": -20,
        "coupon": -25,
        "advertisement": -25,
        "unsubscribe": -25,
        "marketing": -20,
        "deal": -20,
        "limited time": -20,
        "special offer": -25,
        "clearance": -25,
        "buy now": -25,
        "free trial": -20,
        "upgrade today": -20,
        "win": -25,
        "gift": -20,
        "reward": -20,
        "sweepstakes": -30,
        "lottery": -30,
        "cashback": -20,
        "shopping": -20,
        "store": -15,
        "price drop": -20,
        "best deal": -20,
        "exclusive access": -15,
        "member exclusive": -15,
        "subscribe now": -20,
        "join free": -20,
        "no credit card required": -20,
        "spam": -30,
        "junk": -30,
        "opt out": -25,
        "manage preferences": -20,
        "social notification": -15,
        "friend request": -15,
        "new follower": -15,
        "liked your photo": -20,
        "commented on": -15,
        "retweeted": -15,
        "shared": -10,
        "connection request": -10,
        "birthday reminder": -15,
        "anniversary": -10,
        "invite code": -15,
        "referral link": -20,
        "earn money": -30,
        "make money": -30,
        "passive income": -30,
        "get rich": -35,
        "work from home": -25,
        "cheap": -25,
        "best price": -20,
        "save big": -20,
        "advert": -20
    }
}

# Substring weight rules (high impact keywords evaluated on cleaned combined text)
SPECIAL_WEIGHTS = {
    "urgent": 35,
    "immediately": 35,
    "asap": 30,
    "critical": 40,
    "deadline": 40,
    "manager": 20,
    "client": 15,
    "meeting": 10,
    "promotion": -20,
    "newsletter": -10,
    "today": 30,
    "tomorrow": 20,
    "within 2 days": 25,
    "action required": 25,
    "please reply": 20,
    "immediately respond": 30
}

# Category classification keyword libraries & weights (adds points to categories)
CATEGORY_KEYWORDS = {
    "Client": [
        "client", "customer", "partner", "proposal", "contract", "agreement", "invoice", 
        "billing", "external", "vendor", "account manager", "feedback", "pricing", 
        "quotation", "scope of work", "sow", "purchase order", "client meeting", 
        "customer support", "client feedback", "partnercorp", "sales query"
    ],
    "Manager": [
        "manager", "director", "vp", "supervisor", "boss", "executive", "board", 
        "performance review", "one on one", "approval needed", "team lead", "leadership", 
        "management", "sarah", "reporting line", "q3 slides", "deliverables review"
    ],
    "Meeting": [
        "meeting", "schedule", "calendar", "invite", "zoom", "google meet", "teams", 
        "webinar", "conference", "appointment", "call", "discussion", "agenda", 
        "rsvp", "session", "workshop", "time slot", "availability", "interview"
    ],
    "Finance": [
        "invoice", "payment", "billing", "receipt", "wire transfer", "bank", "credit card", 
        "charge", "refund", "transaction", "purchase", "tax", "payroll", "salary", 
        "expense", "budget", "finance", "audit", "account balance", "bank statement"
    ],
    "HR": [
        "hr", "human resources", "recruitment", "interview", "job offer", "benefits", 
        "insurance", "training", "policy", "onboarding", "leave request", "vacation", 
        "holiday", "compliance", "mandatory training", "candidate", "performance review"
    ],
    "Security": [
        "security", "password", "unauthorized", "login", "verification code", "otp", 
        "breach", "compromised", "alert", "2fa", "two-factor", "hacked", "phishing", 
        "privacy", "access granted", "mfa", "reset code", "suspicious", "passcode"
    ],
    "Promotion": [
        "sale", "discount", "offer", "coupon", "deal", "marketing", "promotion", 
        "advertising", "limited time", "shop", "save", "free trial", "pricing plans", 
        "special offer", "clearance", "buy now", "save big", "gift card", "promo"
    ],
    "Newsletter": [
        "newsletter", "digest", "weekly update", "monthly", "subscribe", "blog", 
        "article", "industry news", "techtalk", "read more", "unsubscribe", 
        "publication", "stories", "weekly tech", "bulletin", "feed"
    ],
    "Personal": [
        "friend", "family", "personal", "dinner", "weekend", "plans", "trip", "party", 
        "birthday", "congratulations", "chat", "lunch", "coffee", "catch up", 
        "brother", "sister", "mother", "father"
    ],
    "Development": [
        "development", "git", "github", "gitlab", "commit", "pull request", "pr", 
        "repository", "code review", "deploy", "production", "ci/cd", "jenkins", 
        "build", "api", "database", "bug", "jira", "ticket", "codebase", "backend", 
        "frontend", "programming", "javascript", "python", "css", "html", "logs", "hotfix"
    ],
    "System Notification": [
        "notification", "system", "alert", "auto-generated", "no-reply", "noreply", 
        "automated", "status alert", "monitoring", "aws", "cloud", "server alert", 
        "cron job", "successful", "failed", "ping alert", "backup status", "server", 
        "outage", "crash", "down", "status"
    ]
}
